#!/usr/bin/env python3
"""The table catalogue, generated from the source roster: one class per table a build reads, one attribute per column.

    python tools/catalogue.py            # print the module
    python tools/catalogue.py --check    # exit 1 where build/pack/routes/catalogue.py is stale
    python tools/catalogue.py --write    # rewrite it

A flow names a table as ``T.SpellEffect`` and a column as ``T.SpellEffect.SpellID``,
so a misspelt name is the checker's error rather than the build's. The classes
are read off the roster of sources: the client tables `sources/wago.py`
downloads, with every column their WoWDBDefs definition names; the server
dump's tables `sources/tdb.py` keeps, with the columns it keeps; and the pinned
build's one table. Nothing in the module is written by hand, and the repository
check runs `--check`. The definitions come from the build's own cache; a check
with none cached skips rather than fetching.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "build"))

from pack.sources import dbd  # noqa: E402
from pack.sources.client import DEFINITIONS  # noqa: E402
from pack.sources.tdb import TDB_TABLES  # noqa: E402
from pack.sources.wago import TABLES  # noqa: E402

MODULE = ROOT / "build" / "pack" / "routes" / "catalogue.py"

PINNED = ["SoundKitName"]
"""The tables read from a pinned build rather than the pack's own."""

HEADER = '''"""The tables a flow reads, one class each, its columns the attributes.

Generated by ``tools/catalogue.py`` from the source roster, never edited by hand:
the client tables ``sources/wago.py`` downloads, with every column their
WoWDBDefs definition names; the server dump's tables ``sources/tdb.py``
keeps, with the columns it keeps; and the pinned build's one table. A
localised column carries the ``_lang`` suffix the export gives it, and an
array column is marked, so one slot is ``Name[0]`` and the whole is ``Name[:]``.
"""

from __future__ import annotations

from .expressions import Column, Table
'''


def client_columns(table: str, fetch: bool) -> list[tuple[str, bool]] | None:
    """Each column of a client table as the definition and the export name it,
    and whether it is an array on any build; None where the definition is not
    cached and may not be fetched."""
    if not fetch and not (DEFINITIONS / f"{table}.dbd").exists():
        return None
    definition = dbd.load(table, DEFINITIONS)
    if definition is None:
        raise SystemExit(f"error: {table} has no definition upstream")
    arrays = {entry.name for block in definition.blocks for entry in block.columns if entry.array}
    return [(name, name in arrays) for name, column in definition.columns.items()]


def rendered(name: str, doc: str, columns: list[tuple[str, bool]]) -> str:
    """One table's class."""
    lines = [f"class {name}(Table):", f'    """{doc}"""', ""]
    for column, array in columns:
        lines.append(
            f'    {column} = Column("{column}", array=True)' if array else f'    {column} = Column("{column}")'
        )
    return "\n".join(lines) + "\n"


def generated(fetch: bool) -> str | None:
    """The whole module, or None where a definition is missing and may not be fetched."""
    classes: list[str] = []
    for table in TABLES:
        columns = client_columns(table, fetch)
        if columns is None:
            return None
        classes.append(rendered(table, f"The client's ``{table}``.", columns))
    for table in PINNED:
        columns = client_columns(table, fetch)
        if columns is None:
            return None
        classes.append(rendered(table, f"The pinned build's ``{table}``.", columns))
    for table, kept in TDB_TABLES["world"].items():
        doc = f"The server dump's ``{table}``, the columns the build keeps."
        classes.append(rendered(table, doc, [(column, False) for column in kept]))
    return HEADER + "\n\n" + "\n\n".join(classes)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 where the module is stale")
    ap.add_argument("--write", action="store_true", help="rewrite the module, fetching any definition not cached")
    args = ap.parse_args()
    fresh = generated(fetch=args.write)
    if fresh is None:
        print("catalogue not checked: a table definition is not cached; python tools/catalogue.py --write fetches it")
        return
    if args.write:
        MODULE.write_text(fresh, encoding="utf-8")
        print(f"wrote {MODULE}")
        return
    if not args.check:
        print(fresh)
        return
    if not MODULE.exists() or MODULE.read_text(encoding="utf-8") != fresh:
        sys.exit(f"error: {MODULE} is stale; run python tools/catalogue.py --write")
    print("catalogue current")


if __name__ == "__main__":
    main()
