#!/usr/bin/env python3
"""The route table, read off the registry: every declared field, what it reads, what it lands as.

    python tools/routes.py            # the table, as markdown
    python tools/routes.py --check    # exit 1 where docs/DATA_ROUTES.md carries a stale copy
    python tools/routes.py --write    # rewrite the copy in docs/DATA_ROUTES.md

The declarations in `build/pack/routes/flows.py` are the routes; this prints
them rather than restating them, so the document cannot drift from the code
it describes. The copy lives between two markers in the route document, and
`tools/check.py` runs `--check`.
"""

from __future__ import annotations

import argparse
import importlib
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "build"))

from pack.routes.flow import (  # noqa: E402
    Alternatives,
    Composed,
    Expand,
    Flow,
    Join,
    Lookup,
    Narrow,
    Plan,
    Read,
    Runnable,
    Split,
    Then,
)
from pack.routes.route import DECLARED  # noqa: E402

DOCUMENT = ROOT / "docs" / "DATA_ROUTES.md"
BEGIN = "<!-- routes: generated by tools/routes.py, do not edit -->"
END = "<!-- routes: end -->"


def flows_of(held: Runnable[object]) -> list[Flow]:
    """Every flow under a runnable, in declaration order: a split's trunk, an
    alternative's each plan, a reshaped plan's own."""
    if isinstance(held, Plan):
        return [held.flow]
    if isinstance(held, Then):
        return flows_of(held.plan)
    if isinstance(held, Alternatives):
        return [flow for alternative in held.plans for flow in flows_of(alternative)]
    if isinstance(held, Split):
        return [held.trunk]
    return []


def tables_of(held: Runnable[object]) -> list[str]:
    """The tables a runnable reads, the origin first, joins and expansions after."""
    named: list[str] = []
    for flow in flows_of(held):
        for step in flow.steps:
            if isinstance(step, Read):
                named.append(step.table if step.source == "tables" else f"{step.table} ({step.source})")
            elif isinstance(step, (Join, Expand)):
                named.append(step.table if step.source == "tables" else f"{step.table} ({step.source})")
    return list(dict.fromkeys(named))


def fields_of(held: Runnable[object]) -> list[str]:
    """The other fields a runnable reads, by the paths it names."""
    named = set(held.needs)
    for flow in flows_of(held):
        for step in flow.steps:
            if isinstance(step, Narrow) and isinstance(step.roster, str):
                named.add(step.roster)
            elif isinstance(step, Lookup) and isinstance(step.field, str):
                named.add(step.field)
    return sorted(path for path in named if path not in ("tables", "base", "world", "pinned"))


def described(held: Runnable[object]) -> str:
    """What the declaration says it is, in its own words."""
    if isinstance(held, Composed):
        return f"composed of {', '.join(sorted(set(held.sources.values())))}"
    flows = flows_of(held)
    if isinstance(held, Alternatives):
        return " or ".join(flow.name for flow in flows)
    if isinstance(held, Split):
        return f"{held.trunk.name}, split into {len(held.branches)} landings"
    return flows[0].name if flows else ""


def shape_of(held: Runnable[object]) -> str:
    """The shape a runnable lands in, by its terminal's name."""
    if isinstance(held, Composed):
        return getattr(held.build, "__name__", "record")
    if isinstance(held, Split):
        return getattr(held.record, "__name__", "record")
    if isinstance(held, Then):
        inner = shape_of(held.plan)
        return f"{inner}, then {getattr(held.assemble, '__name__', 'reshaped')}"
    if isinstance(held, Alternatives):
        return shape_of(held.plans[0])
    if isinstance(held, Plan):
        return type(held.terminal).__name__.removeprefix("As").lower()
    return "?"


def rows() -> Iterable[tuple[str, str, str, str, str]]:
    """One row per declared field, in declaration order."""
    importlib.import_module("pack.routes.flows")  # importing it is what registers the declarations
    for field, plans in DECLARED.items():
        for since, held in plans:
            name = f"{field} (from {since})" if since else field
            yield (
                name,
                described(held),
                ", ".join(tables_of(held)) or "none",
                ", ".join(fields_of(held)) or "none",
                shape_of(held),
            )


def table(found: Sequence[tuple[str, ...]]) -> str:
    """The rows as a markdown table, padded the way the document is written."""
    header = ("field", "what it is", "reads", "needs", "lands as")
    widths = [max(len(row[i]) for row in (header, *found)) for i in range(len(header))]
    line = lambda row: "| " + " | ".join(cell.ljust(width) for cell, width in zip(row, widths)) + " |"  # noqa: E731
    rule = "|" + "|".join("-" * (width + 2) for width in widths) + "|"
    return "\n".join([line(header), rule, *(line(row) for row in found)])


def generated() -> str:
    """The whole block, markers included."""
    body = table(list(rows()))
    count = len(DECLARED)
    return (
        f"{BEGIN}\n\n{count} declared fields, in `build/pack/routes/flows.py`, in declaration order:\n\n{body}\n\n{END}"
    )


def current() -> tuple[str, str, str] | None:
    """The document split around its copy of the table, or None where it has none."""
    text = DOCUMENT.read_text(encoding="utf-8")
    start, end = text.find(BEGIN), text.find(END)
    if start < 0 or end < 0:
        return None
    return text[:start], text[start : end + len(END)], text[end + len(END) :]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 where the document's copy is stale")
    ap.add_argument("--write", action="store_true", help="rewrite the document's copy")
    args = ap.parse_args()
    fresh = generated()
    if not (args.check or args.write):
        print(fresh)
        return
    held = current()
    if held is None:
        sys.exit(f"error: {DOCUMENT} carries no route table; add the two markers and run --write")
    before, copy, after = held
    if args.write:
        DOCUMENT.write_text(before + fresh + after, encoding="utf-8")
        print(f"wrote {DOCUMENT}")
        return
    if copy != fresh:
        sys.exit(f"error: {DOCUMENT} carries a stale route table; run python tools/routes.py --write")
    print("route table current")


if __name__ == "__main__":
    main()
